"""Setup Gemini API"""
print("="*60)
print("Google Gemini API Setup")
print("="*60)

print("\n📝 Steps to get FREE Gemini API key:\n")
print("1. Go to: https://makersuite.google.com/app/apikey")
print("   (or https://aistudio.google.com/app/apikey)")
print("\n2. Click 'Create API Key'")
print("\n3. Copy the API key")
print("\n4. Open .env file and update:")
print("   GEMINI_API_KEY=your_actual_key_here")
print("   AI_PROVIDER=gemini")
print("\n5. Install Gemini SDK:")
print("   pip install google-genai")
print("\n6. Test with:")
print("   python test_gemini.py")

print("\n" + "="*60)
print("✨ Gemini Free Tier:")
print("   - 60 requests per minute")
print("   - 1,500 requests per day")
print("   - FREE forever!")
print("="*60)
